# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifier_dev
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata  
    networks:
        - mm_2023

networks:
  mm_2023:
    name: mm_2023
    driver: bridge
volumes:
  db-data:
